postgres:
    image: postgres:9.4
    restart: always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_USER=airflow
        - POSTGRES_DB=airflow

redis:
    image: redis:3
    restart: always
    ports:
        - "6379:6379"

webserver:
    image: jwmarshall/docker-airflow
    restart: always
    # volumes:
    #     - /localpath/to/dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8080:8080"
    links:
        - postgres:postgres
        - redis:redis
        - worker:worker
        - scheduler:scheduler
    command: webserver

flower:
    image: jwmarshall/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "5555:5555"
    links:
        - redis:redis
    command: flower

scheduler:
    image: jwmarshall/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - redis:redis
    command: scheduler

worker:
    image: jwmarshall/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8793:8793"
    links:
        - postgres:postgres
        - redis:redis
    command: worker
